export class CptCodes {
	cptCodeMap = {
		"00104": {"category": "HEAD", "description": "Electroconvulsive Therapy"},
		"00124": {"category": "HEAD", "description": "EAR - Otoscopy"},
		"00126": {"category": "HEAD", "description": "EAR - Tympanotomy/Tympanostomy"},
		"00120": {"category": "HEAD", "description": "EAR - External, middle and inner ear - Other(including biopsy)"},
		"00144": {"category": "HEAD", "description": "EYE - Corneal transplant"},
		"00147": {"category": "HEAD", "description": "EYE - Iredectomy"},
		"00142": {"category": "HEAD", "description": "EYE - Lens"},
		"00148": {"category": "HEAD", "description": "EYE - Ophthalmoscopy"},
		"00145": {"category": "HEAD", "description": "EYE - Vitreoretinal"},
		"00140": {"category": "HEAD", "description": "EYE - Other"},
		"00103": {"category": "HEAD", "description": "EYELID - Reconstructive (e.g., blepharoplasty, ptosis)"},
		//"00192": {"category": "HEAD", "description": "FACIAL BONES - Radical surgery (including prognathism)"},
		//"00190": {"category": "HEAD", "description": "FACIAL BONES - Other"},
		//"00300": {"category": "HEAD", "description": "INTEGUMENTARY SYSTEM, MUSCLES, NERVES"},
		"00211": {"category": "HEAD", "description": "INTRACRANIAL - Craniotomy/Craniectomy for hematoma"},
		"00212": {"category": "HEAD", "description": "INTRACRANIAL - Subdural taps"},
		"00214": {"category": "HEAD", "description": "INTRACRANIAL - Burr holes, including ventriculography"},
		"00216": {"category": "HEAD", "description": "INTRACRANIAL - Vascular procedures"},
		"00215": {"category": "HEAD", "description": "INTRACRANIAL - Cranioplasty extradural"},
		"00218": {"category": "HEAD", "description": "INTRACRANIAL - Procedures in sitting position"},
		"00220": {"category": "HEAD", "description": "INTRACRANIAL - CSF shunting procedures"},
		"00222": {"category": "HEAD", "description": "INTRACRANIAL - Electrocoagulation of intracranial nerve"},
		"00210": {"category": "HEAD", "description": "INTRACRANIAL - Not otherwise specified"},
		"00176": {"category": "HEAD", "description": "INTRAORAL - Radical surgery"},
		"00172": {"category": "HEAD", "description": "INTRAORAL - Repair of cleft palate"},
		"00174": {"category": "HEAD", "description": "INTRAORAL - Excision of retropharyngeal tumor"},
		"00170": {"category": "HEAD", "description": "INTRAORAL - Other (including biopsy)"},
		"00102": {"category": "HEAD", "description": "LIP - Cleft lip repair"},
		//"00300": {"category": "HEAD", "description": "MUSCLES, NERVES, INTEGUMENTARY SYSTEM"},
		"00164": {"category": "HEAD", "description": "NOSE/SINUSES - Biopsy, soft tissue"},
		"00162": {"category": "HEAD", "description": "NOSE/SINUSES - Radical surgery"},
		"00160": {"category": "HEAD", "description": "NOSE/SINUSES- Not otherwise specified"},
		"00100": {"category": "HEAD", "description": "SALIVARY GLANDS (including biopsy)"},
		//"00192": {"category": "HEAD", "description": "SKULL - Radical surgery (including prognathism)"},
		//"00190": {"category": "HEAD", "description": "SKULL - Other"},
		"00350": {"category": "NECK", "description": "BLOOD VESSELS - Major"},
		"00352": {"category": "NECK", "description": "BLOOD VESSELS - Simple ligation(temporal artery biopsy/ligation)"},
		//"00320": {"category": "NECK", "description": "ESOPHAGUS (in neck only)"},
		//"00320": {"category": "NECK", "description": "LARYNX/TRACHEA, age > 1 year"},
		"00326": {"category": "NECK", "description": "LARYNX/TRACHEA, children < 1 year old"},
		//"00300": {"category": "NECK", "description": "INTEGUMENTARY SYSTEM, MUSCLES, NERVES"},
		//"00320": {"category": "NECK", "description": "LYMPHATIC SYSTEM"},
		"00322": {"category": "NECK", "description": "THYROID - Needle biopsy"},
		//"00320": {"category": "NECK", "description": "THYROID-Other"},
		"00410": {"category": "THORAX", "description": "Electrical conversion of arrhythmias"},
		"00402": {"category": "THORAX", "description": "BREAST - RECONSTRUCTIVE PROCEDURE (augmentation or reduction)"},
		"00404": {"category": "THORAX", "description": "BREAST - radical or modified radical"},
		"00406": {"category": "THORAX", "description": "BREAST - radical or modified radical with int mammary node dissection"},
		//"00454": {"category": "THORAX", "description": "CLAVICLE - Biopsy"},
		"00452": {"category": "THORAX", "description": "CLAVICLE - Radical surgery"},
		"00450": {"category": "THORAX", "description": "CLAVICLE and SCAPULA - Not otherwise specified"},
		//"00400": {"category": "THORAX", "description": "INTEGUMENTARY SYSTEM, MUSCLES, NERVES  - Anterior trunk"},
		//"00300": {"category": "THORAX", "description": "INTEGUMENTARY SYSTEM, MUSCLES, NERVES  - Posterior trunk"},
		//"00454": {"category": "THORAX", "description": "RIBS/STERNUM - Biopsy"},
		"00472": {"category": "THORAX", "description": "RIBS/STERNUM - Thoracoplasty "},
		"00474": {"category": "THORAX", "description": "RIBS/STERNUM - Radical procedures (e.g., pectus excavatum)"},
		"00470": {"category": "THORAX", "description": "RIBS/STERNUM - Partial resection, sternal wire removal, other"},
		"00522": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - needle biopsy of pleura"},
		"00528": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - mediastinoscopy/diagnostic thoracoscopy, not utilizing 1 lung vent"},
		"00529": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - mediastinoscopy/diagnostic thoracoscopy, utilizing 1 lung vent"},
		"00524": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - pneumocentesis"},
		"00550": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - sternal debridement"},
		"00537": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - Cardiac electrophysiologic procedures"},
		"00530": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - Transvenous pacemaker"},
		"00534": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - Transvenous pacing cardioverter-defibrillator"},
		"00532": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - Anesthesia for central venous access"},
		"00520": {"category": "INTRATHORACIC", "description": "CLOSED CHEST - Other, including bronchoscopy"},
		"00566": {"category": "INTRATHORACIC", "description": "HEART - CORONARY ARTERY BYPASS GRAFTING WITHOUT PUMP OXYGENATOR"},
		"00567": {"category": "INTRATHORACIC", "description": "HEART - CORONARY ARTERY BYPASS GRAFTING WITH PUMP OXYGENATOR"},
		"00580": {"category": "INTRATHORACIC", "description": "HEART - Heart transplant or heart/lung transplant"},
		"00560": {"category": "INTRATHORACIC", "description": "HEART/PERICARDIUM/GREAT VESSELS - without pump oxygenator "},
		"00561": {"category": "INTRATHORACIC", "description": "HEART/PERICARDIUM/GREAT VESSELS - with pump oxygenator, age < 1 year "},
		"00562": {"category": "INTRATHORACIC", "description": "HEART/PERICARDIUM/GREAT VESSELS - with pump oxygenator, age > 1 year "},
		"00563": {"category": "INTRATHORACIC", "description": "HEART/PERICARDIUM/GREAT VESSELS - with pump oxygenator and circulatory arrest"},
		"00541": {"category": "INTRATHORACIC", "description": "THORACOTOMY/SURGICAL THORACOSCOPY, utilizing 1 lung ventilation"},
		"00542": {"category": "INTRATHORACIC", "description": "THORACOTOMY/SURGICAL THORACOSCOPY, decortication"},
		"00546": {"category": "INTRATHORACIC", "description": "THORACOTOMY/SURGICAL THORACOSCOPY, pulmonary resection with thoracoplasty"},
		"00539": {"category": "INTRATHORACIC", "description": "THORACOTOMY/SURGICAL THORACOSCOPY, trachea/bronchial reconstruction"},
		"00548": {"category": "INTRATHORACIC", "description": "THORACOTOMY/SURGICAL THORACOSCOPY, trachea and bronchi"},
		"00500": {"category": "INTRATHORACIC", "description": "THORACOTOMY/SURGICAL THORACOSCOPY, esophagus"},
		"00540": {"category": "INTRATHORACIC", "description": "THORACOTOMY/SURGICAL THORACOSCOPY, other for lungs, pleura, diaphragm, mediastinum"},
		"00640": {"category": "SPINE/SPINAL CORD", "description": "MANIPULATION OR CLOSED PROCEDURES on cervical, thoracic or lumbar spine"},
		"00670": {"category": "SPINE/SPINAL CORD", "description": "EXTENSIVE SPINE AND SPINAL CORD (e.g. instrumentation or vascular)"},
		"00604": {"category": "SPINE/SPINAL CORD", "description": "CERVICAL, sitting position"},
		"00600": {"category": "SPINE/SPINAL CORD", "description": "CERVICAL, other"},
		"00622": {"category": "SPINE/SPINAL CORD", "description": "THORACIC, thoracolumbar sympathectomy"},
		"00625": {"category": "SPINE/SPINAL CORD", "description": "THORACIC, via anterior approach, not 1 lung ventilation"},
		"00626": {"category": "SPINE/SPINAL CORD", "description": "THORACIC, via anterior approach, with 1 lung ventilation"},
		"00620": {"category": "SPINE/SPINAL CORD", "description": "THORACIC, other"},
		"00632": {"category": "SPINE/SPINAL CORD", "description": "LUMBAR, lumbar sympathectomy"},
		"00634": {"category": "SPINE/SPINAL CORD", "description": "LUMBAR, chemonucleolysis"},
		"00635": {"category": "SPINE/SPINAL CORD", "description": "LUMBAR, diagnostic or therapeutic lumbar puncture"},
		"00630": {"category": "SPINE/SPINAL CORD", "description": "LUMBAR, other"},
		"00740": {"category": "UPPER ABDOMEN", "description": "UPPER GI ENDOSCOPY, proximal to duodenum"},
		"00752": {"category": "UPPER ABDOMEN", "description": "Lumbar and ventral (incisional) hernias and/or wound dehiscence"},
		"00754": {"category": "UPPER ABDOMEN", "description": "Omphalocele repair"},
		"00750": {"category": "UPPER ABDOMEN", "description": "Hernia repairs, other in upper abdominal wall"},
		"00702": {"category": "UPPER ABDOMEN", "description": "UPPER ANTERIOR ABDOMINAL WALL, percutaneous liver biopsy"},
		"00700": {"category": "UPPER ABDOMEN", "description": "UPPER ANTERIOR ABDOMINAL WALL, other"},
		"00730": {"category": "UPPER ABDOMEN", "description": "UPPER POSTERIOR ABDOMINAL WALL "},
		"00756": {"category": "UPPER ABDOMEN", "description": "Transabdominal repair of diaphragmatic hernia"},
		"00770": {"category": "UPPER ABDOMEN", "description": "Major abdominal blood vessels (eg: Pancreatic allograft transplantation)"},
		"00792": {"category": "UPPER ABDOMEN", "description": "INTRAPERITONEAL - Partial hepatectomy or mgmt of liver hemorrhage"},
		"00794": {"category": "UPPER ABDOMEN", "description": "INTRAPERITONEAL - Pancreatectomy, partial or total (e.g. Whipple)"},
		"00796": {"category": "UPPER ABDOMEN", "description": "INTRAPERITONEAL - Liver transplant (recipient)"},
		"00797": {"category": "UPPER ABDOMEN", "description": "INTRAPERITONEAL - Gastric restrictive procedure for morbid obesity"},
		"00790": {"category": "UPPER ABDOMEN", "description": "INTRAPERITONEAL - Other including laparoscopy"},
		"00810": {"category": "LOWER ABDOMEN", "description": "LOWER GI ENDOSCOPY, distal to duodenum"},
		"00832": {"category": "LOWER ABDOMEN", "description": "Ventral and incisional hernias"},
		"00836": {"category": "LOWER ABDOMEN", "description": "Hernia repairs, < 37 weeks gest. age at birth and < 50 weeks gest. age at repair"},
		"00834": {"category": "LOWER ABDOMEN", "description": "Hernia repair, < 1 year of age"},
		"00830": {"category": "LOWER ABDOMEN", "description": "Hernia repairs, other"},
		"00802": {"category": "LOWER ABDOMEN", "description": "Panniculectomy"},
		"00800": {"category": "LOWER ABDOMEN", "description": "LOWER ANTERIOR ABDOMINAL WALL, other"},
		"00820": {"category": "LOWER ABDOMEN", "description": "LOWER POSTERIOR ABDOMINAL WALL"},
		"00862": {"category": "LOWER ABDOMEN", "description": "EXTRAPERITONEAL - Renal, including upper one-third of ureter or donor nephrectomy"},
		"00864": {"category": "LOWER ABDOMEN", "description": "EXTRAPERITONEAL - Total cystectomy"},
		"00865": {"category": "LOWER ABDOMEN", "description": "EXTRAPERITONEAL - Radical prostatectomy"},
		"00866": {"category": "LOWER ABDOMEN", "description": "EXTRAPERITONEAL - Adrenalectomy"},
		"00868": {"category": "LOWER ABDOMEN", "description": "EXTRAPERITONEAL - Renal transplant"},
		"00870": {"category": "LOWER ABDOMEN", "description": "EXTRAPERITONEAL - Cystolithotomy"},
		"00860": {"category": "LOWER ABDOMEN", "description": "EXTRAPERITONEAL - Other, including urinary tract"},
		"00842": {"category": "LOWER ABDOMEN", "description": "INTRAPERITONEAL - Amniocentesis"},
		"00844": {"category": "LOWER ABDOMEN", "description": "INTRAPERITONEAL - Abdominoperineal resection"},
		"00846": {"category": "LOWER ABDOMEN", "description": "INTRAPERITONEAL - Radical hysterectomy"},
		"00848": {"category": "LOWER ABDOMEN", "description": "INTRAPERITONEAL - Pelvic extenteration"},
		"00851": {"category": "LOWER ABDOMEN", "description": "INTRAPERITONEAL - Tubal ligation/transection"},
		"00840": {"category": "LOWER ABDOMEN", "description": "INTRAPERITONEAL - Other including laparoscopy"},
		"00872": {"category": "LOWER ABDOMEN", "description": "Lithotripsy Extracorporeal Shock wave with water bath"},
		"00873": {"category": "LOWER ABDOMEN", "description": "Lithotripsy Extracorporeal Shock wave without water bath"},
		"00882": {"category": "LOWER ABDOMEN", "description": "Inferior vena cava ligation "},
		"00880": {"category": "LOWER ABDOMEN", "description": "Major lower abdominal vessels, other"},
		//"00400": {"category": "PERINEUM", "description": "Integumentary system"},
		"00902": {"category": "PERINEUM", "description": "ANORECTAL, including anorectal endoscopy or biopsy"},
		"00906": {"category": "PERINEUM", "description": "FEMALE GENITALIA - Vulvectomy"},
		"00942": {"category": "PERINEUM", "description": "FEMALE GENITALIA - Vaginectomy, colpotomy, colporrhaphy, open urethral procedures"},
		"00944": {"category": "PERINEUM", "description": "FEMALE GENITALIA - Vaginal hysterectomy"},
		"00948": {"category": "PERINEUM", "description": "FEMALE GENITALIA - Cervical cerclage"},
		"00950": {"category": "PERINEUM", "description": "FEMALE GENITALIA - Culdoscopy "},
		"00952": {"category": "PERINEUM", "description": "FEMALE GENITALIA - Hysteroscopy, hysterosalpingography"},
		"00940": {"category": "PERINEUM", "description": "FEMALE GENITALIA - Other, including biopsy of labia, vagina, cervix, endometrium"},
		"00921": {"category": "PERINEUM", "description": "MALE GENITALIA - Vasectomy"},
		"00922": {"category": "PERINEUM", "description": "MALE GENITALIA - Seminal vesicles"},
		"00924": {"category": "PERINEUM", "description": "MALE GENITALIA - Undescended testis"},
		"00926": {"category": "PERINEUM", "description": "MALE GENITALIA - Radical orchiectomy, inguinal"},
		"00928": {"category": "PERINEUM", "description": "MALE GENITALIA - Radical orchiectomy, abdominal"},
		"00930": {"category": "PERINEUM", "description": "MALE GENITALIA - Orchipexy"},
		"00932": {"category": "PERINEUM", "description": "MALE GENITALIA - Complete amputation of penis"},
		"00934": {"category": "PERINEUM", "description": "MALE GENITALIA - Radical amputation of penis with bilateral lymphadenectomy"},
		"00936": {"category": "PERINEUM", "description": "MALE GENITALIA - Radical amputation of penis with bilateral inguinal and iliac lymphadenectomy"},
		"00938": {"category": "PERINEUM", "description": "MALE GENITALIA - Insertion of penile prosthesis"},
		"00920": {"category": "PERINEUM", "description": "MALE GENITALIA - Other, including open urethral procedures"},
		"00904": {"category": "PERINEUM", "description": "Radical perineal procedure"},
		"00908": {"category": "PERINEUM", "description": "Perineal prostatectomy"},
		"00912": {"category": "PERINEUM", "description": "TRANSURETHRAL - Resection of bladder tumor(s) "},
		"00914": {"category": "PERINEUM", "description": "TRANSURETHRAL - Resection of prostate"},
		"00916": {"category": "PERINEUM", "description": "Post-Transurethral Resection bleeding"},
		"00918": {"category": "PERINEUM", "description": "TRANSURETHRAL - Other including urethrocystoscopy for ureteral calculus"},
		"00910": {"category": "PERINEUM", "description": "TRANSURETHRAL - Other including urethrocystoscopy for other"},
		"01112": {"category": "PELVIS (EXCEPT HIP)", "description": "Bone marrow aspiration/biopsy, anterior or posterior iliac crest"},
		"01120": {"category": "PELVIS (EXCEPT HIP)", "description": "Bony pelvic procedures"},
		"01130": {"category": "PELVIS (EXCEPT HIP)", "description": "Body cast application or revision"},
		"01140": {"category": "PELVIS (EXCEPT HIP)", "description": "Interpelviabdominal (hindquarter) amputation"},
		"01150": {"category": "PELVIS (EXCEPT HIP)", "description": "Radical procedures for pelvic tumor, except hindquarter amputation"},
		"01160": {"category": "PELVIS (EXCEPT HIP)", "description": "Closed procedures involving symphysis pubis or sacroiliac joint"},
		"01170": {"category": "PELVIS (EXCEPT HIP)", "description": "Open procedures involving symphysis pubis or sacroiliac joint"},
		"01173": {"category": "PELVIS (EXCEPT HIP)", "description": "Open repair of fracture disruption of pelvis or column fracture involving acetabulum"},
		"01180": {"category": "PELVIS (EXCEPT HIP)", "description": "Obturator neurectomy, extrapelvic"},
		"01190": {"category": "PELVIS (EXCEPT HIP)", "description": "Obturator neurectomy, intrapelvic"},
		"00400": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "Integumentary system"},
		"01200": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "HIP - Closed procedures on hip joint"},
		"01202": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "HIP - Arthroscopic procedures of hip joint"},
		"01212": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "HIP - Disarticulation"},
		"01214": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "HIP - Total hip artroplasty"},
		"01215": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "HIP - Revision total hip arthroplasty"},
		"01210": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "HIP - Other open procedures "},
		"01220": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "UPPER TWO-THIRDS OF FEMUR - Closed procedures"},
		"01232": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "UPPER TWO-THIRDS OF FEMUR - Amputation"},
		"01234": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "UPPER TWO-THIRDS OF FEMUR - Radical resection"},
		"01230": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "UPPER TWO-THIRDS OF FEMUR - Other open procedure"},
		"01250": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "NERVES, MUSCLES, TENDONS, FASCIA, AND BURSAE OF UPPER LEG"},
		"01260": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "VEINS, including exploration"},
		"01272": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "ARTERIES - Femoral artery ligation"},
		"01274": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "ARTERIES - Femoral artery embolectomy"},
		//"01844": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "ARTERIES - Dialysis access procedure"},
		"01270": {"category": "UPPER LEG (EXCEPT KNEE)", "description": "ARTERIES - Other, including bypass graft"},
		//"00400": {"category": "KNEE/POPLITEAL", "description": "Integumentary system"},
		"01320": {"category": "KNEE/POPLITEAL", "description": "NERVES, MUSCLES, TENDONS, FASCIA, BURSAE"},
		"01340": {"category": "KNEE/POPLITEAL", "description": "LOWER ONE-THIRD OF FEMUR - Closed procedures "},
		"01360": {"category": "KNEE/POPLITEAL", "description": "LOWER ONE-THIRD OF FEMUR - Open procedure "},
		"01420": {"category": "KNEE/POPLITEAL", "description": "KNEE JOINT - Cast application, removal or repair"},
		"01380": {"category": "KNEE/POPLITEAL", "description": "KNEE JOINT - Closed procedures "},
		"01382": {"category": "KNEE/POPLITEAL", "description": "KNEE JOINT - Diagnostic arthroscopic procedures "},
		"01402": {"category": "KNEE/POPLITEAL", "description": "KNEE JOINT - Total knee arthroplasty"},
		"01404": {"category": "KNEE/POPLITEAL", "description": "KNEE - Disarticulation at"},
		"01400": {"category": "KNEE/POPLITEAL", "description": "KNEE JOINT - Other open or surgical arthroscopic procedures"},
		"01390": {"category": "KNEE/POPLITEAL", "description": "UPPER ENDS OF TIBIA, FIBULA, PATELLA - Closed procedures"},
		"01392": {"category": "KNEE/POPLITEAL", "description": "UPPER ENDS OF TIBIA, FIBULA, PATELLA - Open procedures"},
		"01442": {"category": "KNEE/POPLITEAL", "description": "ARTERIES - Popliteal thromboendarterectomy"},
		"01444": {"category": "KNEE/POPLITEAL", "description": "ARTERIES - Popliteal excision/graft/repair for occlusion or aneurysm"},
		"01432": {"category": "KNEE/POPLITEAL", "description": "ARTERIES/VEINS - Arteriovenous fistula"},
		"01440": {"category": "KNEE/POPLITEAL", "description": "ARTERIES - Other"},
		"01430": {"category": "KNEE/POPLITEAL", "description": "VEINS - Other"},
		//"00400": {"category": "LOWER LEG/ANKLE/FOOT", "description": "Integumentary system"},
		"01490": {"category": "LOWER LEG/ANKLE/FOOT", "description": "Lower leg cast application, removal, repair"},
		"01462": {"category": "LOWER LEG/ANKLE/FOOT", "description": "Closed procedures"},
		"01472": {"category": "LOWER LEG/ANKLE/FOOT", "description": "NERVES, MUSCLES, TENDONS, FASCIA - Repair of Achilles tendon"},
		"01474": {"category": "LOWER LEG/ANKLE/FOOT", "description": "NERVES, MUSCLES, TENDONS, FASCIA - Gastrocnemius recession (e.g., Strayer Procedure)"},
		"01470": {"category": "LOWER LEG/ANKLE/FOOT", "description": "NERVES, MUSCLES, TENDONS, FASCIA - Other"},
		"01464": {"category": "LOWER LEG/ANKLE/FOOT", "description": "Arthroscopic procedures"},
		"01486": {"category": "LOWER LEG/ANKLE/FOOT", "description": "BONES - Total ankle replacement"},
		"01482": {"category": "LOWER LEG/ANKLE/FOOT", "description": "BONES - Radical resection, including below knee amputation"},
		"01484": {"category": "LOWER LEG/ANKLE/FOOT", "description": "BONES - Tibia or fibula osteotomy or osteoplasty"},
		"01480": {"category": "LOWER LEG/ANKLE/FOOT", "description": "BONES - Other open procedure"},
		"01502": {"category": "LOWER LEG/ANKLE/FOOT", "description": "ARTERIES - Embolectomy, direct or with catheter"},
		"01500": {"category": "LOWER LEG/ANKLE/FOOT", "description": "ARTERIES - Other, including bypass graft"},
		"01522": {"category": "LOWER LEG/ANKLE/FOOT", "description": "VEINS - Thrombectomy, direct or with catheter"},
		"01520": {"category": "LOWER LEG/ANKLE/FOOT", "description": "VEINS - Other"},
		//"00400": {"category": "SHOULDER/AXILLA", "description": "Integumentary system"},
		"01682": {"category": "SHOULDER/AXILLA", "description": "Shoulder spica"},
		"01680": {"category": "SHOULDER/AXILLA", "description": "Shoulder cast application, removal, repair"},
		"01620": {"category": "SHOULDER/AXILLA", "description": "Closed procedures on humeral head/neck, sternoclavicular, acromioclavicular, shoulder joint"},
		"01610": {"category": "SHOULDER/AXILLA", "description": "NERVES, MUSCLES, TENDONS, FASCIA, BURSAE"},
		"01622": {"category": "SHOULDER/AXILLA", "description": "Diagnostic arthroscopic procedures"},
		"01634": {"category": "SHOULDER/AXILLA", "description": "BONES - Shoulder disarticulation"},
		"01636": {"category": "SHOULDER/AXILLA", "description": "BONES - Interthoracoscapular (forequarter) amputation"},
		"01638": {"category": "SHOULDER/AXILLA", "description": "BONES - Total shoulder replacement"},
		"01630": {"category": "SHOULDER/AXILLA", "description": "BONES - Other open or surgical arthroscopic procedures"},
		"01652": {"category": "SHOULDER/AXILLA", "description": "ARTERIES - Axillary-brachial aneurysm"},
		"01656": {"category": "SHOULDER/AXILLA", "description": "ARTERIES - Axillary-femoral (includes ax-popliteal and ax-tibial) bypass"},
		"01654": {"category": "SHOULDER/AXILLA", "description": "ARTERIES - Other bypass graft"},
		"01650": {"category": "SHOULDER/AXILLA", "description": "ARTERIES - Other"},
		"01670": {"category": "SHOULDER/AXILLA", "description": "VEINS"},
		//"00400": {"category": "UPPER ARM/ELBOW", "description": "Integumentary system"},
		"01730": {"category": "UPPER ARM/ELBOW", "description": "Closed procedures"},
		"01712": {"category": "UPPER ARM/ELBOW", "description": "NERVES, MUSCLES, TENDONS, FASCIA, BURSAE - Open tenotomy, elbow to shoulder"},
		"01714": {"category": "UPPER ARM/ELBOW", "description": "NERVES, MUSCLES, TENDONS, FASCIA, BURSAE - Tenoplasty, elbow to shoulder"},
		"01716": {"category": "UPPER ARM/ELBOW", "description": "NERVES, MUSCLES, TENDONS, FASCIA, BURSAE - Tenodesis, rupture of long tendon of biceps"},
		"01710": {"category": "UPPER ARM/ELBOW", "description": "NERVES, MUSCLES, TENDONS, FASCIA, BURSAE - Other"},
		"01732": {"category": "UPPER ARM/ELBOW", "description": "Diagnostic arthroscopic procedures"},
		"01742": {"category": "UPPER ARM/ELBOW", "description": "BONES - Osteotomy of humerus"},
		"01744": {"category": "UPPER ARM/ELBOW", "description": "BONES - Repair of nonunion or malunion of humerus"},
		"01756": {"category": "UPPER ARM/ELBOW", "description": "BONES - Radical procedures, includes amputation and limb salvage procedures"},
		"01758": {"category": "UPPER ARM/ELBOW", "description": "BONES - Excision of cyst or tumor of humerus"},
		"01760": {"category": "UPPER ARM/ELBOW", "description": "BONES - Total elbow replacement"},
		"01740": {"category": "UPPER ARM/ELBOW", "description": "BONES - Other open or surgical arthroscopic procedures"},
		"01772": {"category": "UPPER ARM/ELBOW", "description": "ARTERIES - Embolectomy"},
		//"01844": {"category": "UPPER ARM/ELBOW", "description": "ARTERIES - Dialysis access"},
		"01770": {"category": "UPPER ARM/ELBOW", "description": "ARTERIES - Other"},
		"01782": {"category": "UPPER ARM/ELBOW", "description": "VEINS - Phleborrhaphy"},
		"01780": {"category": "UPPER ARM/ELBOW", "description": "VEINS - Other"},
		////"00400": {"category": "FOREARM/WRIST/HAND", "description": "Integumentary system"},
		"01860": {"category": "FOREARM/WRIST/HAND", "description": "Cast application, removal, repair"},
		"01820": {"category": "FOREARM/WRIST/HAND", "description": "Closed procedures"},
		"01810": {"category": "FOREARM/WRIST/HAND", "description": "NERVES, MUSCLES, TENDONS, FASCIA, BURSAE"},
		"01829": {"category": "FOREARM/WRIST/HAND", "description": "Diagnostic arthroscopic procedures of the wrist"},
		"01832": {"category": "FOREARM/WRIST/HAND", "description": "BONES - Total wrist replacement"},
		"01830": {"category": "FOREARM/WRIST/HAND", "description": "BONES - Other open or surgical arthroscopic/endoscopic procedures"},
		"01842": {"category": "FOREARM/WRIST/HAND", "description": "ARTERIES- Embolectomy"},
		//"01844": {"category": "FOREARM/WRIST/HAND", "description": "ARTERIES - Vascular shunt or revision any type (e.g., dialysis)"},
		"01840": {"category": "FOREARM/WRIST/HAND", "description": "ARTERIES - Other procedures"},
		"01852": {"category": "FOREARM/WRIST/HAND", "description": "VEINS - Phleborrhaphy"},
		"01850": {"category": "FOREARM/WRIST/HAND", "description": "VEINS - Other"},
		"01916": {"category": "RADIOLOGY", "description": "Diagnostic arteriography/venography"},
		"01920": {"category": "RADIOLOGY", "description": "Cardiac catheterization, including coronary angiography, ventriculography (not Swan-Ganz)"},
		"01922": {"category": "RADIOLOGY", "description": "Non-invasive imaging or radiation therapy"},
		"01925": {"category": "RADIOLOGY", "description": "INTERVENTIONAL INVOLVING ARTERIAL SYSTEM - Carotid or coronary"},
		"01926": {"category": "RADIOLOGY", "description": "INTERVENTIONAL INVOLVING ARTERIAL SYSTEM - Intracranial, intracardiac, or aortic"},
		"01924": {"category": "RADIOLOGY", "description": "INTERVENTIONAL INVOLVING ARTERIAL SYSTEM - Other"},
		"01931": {"category": "RADIOLOGY", "description": "INTERVENTIONAL INVOLVING VENOUS/LYMPHATICS - Intrahepatic or portal (e.g., TIPS)"},
		"01932": {"category": "RADIOLOGY", "description": "INTERVENTIONAL INVOLVING VENOUS/LYMPHATICS - Intrathoracic or jugular"},
		"01933": {"category": "RADIOLOGY", "description": "INTERVENTIONAL INVOLVING VENOUS/LYMPHATICS - Intracranial"},
		"01930": {"category": "RADIOLOGY", "description": "INTERVENTIONAL INVOLVING VENOUS/LYMPHATICS - Other"},
		"01935": {"category": "RADIOLOGY", "description": "SPINE/SPINAL CORD - Diagnostic"},
		"01936": {"category": "RADIOLOGY", "description": "SPINE/SPINAL CORD - Therapeutic"},
		"01951": {"category": "BURN EXCISIONS/DEBRIDEMENT", "description": "SECOND AND THIRD DEGREE, any site, TBSA treated < 4% TBSA"},
		"01952": {"category": "BURN EXCISIONS/DEBRIDEMENT", "description": "SECOND AND THIRD DEGREE, any site, TBSA treated 4-9% TBSA"},
		"01953": {"category": "BURN EXCISIONS/DEBRIDEMENT", "description": "Each additional 9% TBSA "},
		"01958": {"category": "OBSTETRIC ANESTHESIA", "description": "External cephalic version procedure"},
		"01960": {"category": "OBSTETRIC ANESTHESIA", "description": "Vaginal delivery only"},
		"01961": {"category": "OBSTETRIC ANESTHESIA", "description": "Cesarean delivery only"},
		"01962": {"category": "OBSTETRIC ANESTHESIA", "description": "Urgent hysterectomy following delivery"},
		"01963": {"category": "OBSTETRIC ANESTHESIA", "description": "Cesarean hysterectomy without any labor anesthesia care"},
		"01965": {"category": "OBSTETRIC ANESTHESIA", "description": "Incomplete or missed abortion procedures"},
		"01966": {"category": "OBSTETRIC ANESTHESIA", "description": "Induced abortion procedures"},
		"01667": {"category": "OBSTETRIC ANESTHESIA", "description": "Neuraxial labor analgesia/anesthesia for planned vaginal delivery"},
		"01968": {"category": "OBSTETRIC ANESTHESIA", "description": "Cesarean delivery following neuraxial labor anesthesia"},
		"01969": {"category": "OBSTETRIC ANESTHESIA", "description": "Cesarean hysterectomy following neuraxial labor anesthesia"},
		"01990": {"category": "OTHER PROCEDURES", "description": "Physiological support for harvesting organ(s) from brain dead patient"},
		"01991": {"category": "OTHER PROCEDURES", "description": "Diagnostic or therapeutic nerve blocks and injections (when block is performed by a different provider), not prone position"},
		"01992": {"category": "OTHER PROCEDURES", "description": "Diagnostic or therapeutic nerve blocks and injections, PRONE POSITION (when block is performed by a different provider)"},
		"01996": {"category": "OTHER PROCEDURES", "description": "Daily hospital management of epidural or subarachnoid continuous drug administration"},
		"01999": {"category": "OTHER PROCEDURES", "description": "UNLISTED ANESTHESIA PROCEDURE(S)"}
	};
}
